# Generated by Django 2.2.7 on 2019-12-13 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shelf', '0002_auto_20191213_2141'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='genre',
            field=models.CharField(choices=[('Action', 'Action'), ('Adventure', 'Adventure'), ('Arcade', 'Arcade'), ('Educational', 'Educational'), ('Family', 'Family'), ('Fighting', 'Fighting'), ('First Person Shooter', 'First Person ShooteR'), ('Fitness', 'Fitness'), ('Horror', 'Horror'), ('Music and Rhythm', 'Music and Rhythm'), ('Party', 'Party'), ('Platformer', 'Platformer'), ('Puzzle', 'Puzzle'), ('Racing', 'Racing'), ('RPG', 'Role Playing Game (RPG)'), ('Shooter', 'Shooter'), ('Simulation', 'Simulation'), ('Sports', 'Sports'), ('Strategy', 'Strategy')], default='Action', max_length=50),
        ),
        migrations.AddField(
            model_name='game',
            name='platform',
            field=models.CharField(choices=[('PS4', 'Playstation 4'), ('PS3', 'Playstation 3'), ('PS2', 'Playstation 2'), ('PSX', 'Playstation'), ('PSVITA', 'PS VITA'), ('PSVR', 'Playstation VR')], default='PS4', max_length=50),
        ),
    ]
