# Generated by Django 2.2.7 on 2019-12-13 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shelf', '0004_auto_20191213_2219'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='num_of_players',
            field=models.CharField(choices=[('1', '1'), ('2', '1-2'), ('3', '1-3'), ('4', '1-4')], default='1', max_length=2),
        ),
    ]
