# Generated by Django 2.2.7 on 2019-12-15 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shelf', '0006_game_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='box_art',
            field=models.ImageField(blank=True, null=True, upload_to='boxart/'),
        ),
    ]
