# Generated by Django 2.2.7 on 2019-12-15 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shelf', '0007_auto_20191215_2058'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='box_art',
            field=models.ImageField(upload_to='boxart/'),
        ),
    ]
